#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 连接
    username: 用户名
    password: 密码
  devtools:
    restart:
    #热部署生效
    enabled: true
    #设置重启的目录
    #additional-paths: src/main/java
    #classpath目录下的WEB-INF文件夹内容修改不重启
    exclude: WEB-INF/**

server:
  #端口号
  port: 8888
  #项目名，如果不设定，默认是 /
  #context-path: /demo
###############################################


#   thymeleaf 相关设置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
#spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，
#改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
#LEGACYHTML5需要搭配一个额外的库NekoHTML才可用
#		<dependency>
#			<groupId>net.sourceforge.nekohtml</groupId>
#			<artifactId>nekohtml</artifactId>
#			<version>1.9.15</version>
#		</dependency>


###############################################



#开MYBATIS日志打印 修改level及包名级别为debug 设置日志保存目录
logging:
  level:
    net.vv2.baby.mapper: DEBUG
  file: var/log/myapp.log


  ###############################################